spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qing_cheng_auth
    username: root
    password: admin123
    druid:
      initial-size: 20
      max-active: 20
      min-idle: 20
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      #password: admin123
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 8
          min-idle: 0
      connect-timeout: 1000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080

# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: Copyright 2024 Shey all rights reserved.
#    enable-home-custom: true
#    home-custom-location: classpath:markdown/home.md
#    home-custom-path: classpath:markdown/home.md


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true